"""firstname->first_name, lastname->last_name in user_accounts

Revision ID: 82ee18b8ca9b
Revises: a3f5448f3868
Create Date: 2026-06-30 10:10:29.988849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '82ee18b8ca9b'
down_revision: Union[str, Sequence[str], None] = 'a3f5448f3868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['uid'])
    op.add_column('user_accounts', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_accounts', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    op.drop_column('user_accounts', 'firstname')
    op.drop_column('user_accounts', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_accounts', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'last_name')
    op.drop_column('user_accounts', 'first_name')
    op.drop_constraint(None, 'books', type_='unique')
    # ### end Alembic commands ###
