"""added unique constraint to the reviews table for user_uid and book_uid

Revision ID: a9631c9a2a00
Revises: a444b05c8fe4
Create Date: 2026-09-10 17:10:22.597276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a9631c9a2a00'
down_revision: Union[str, Sequence[str], None] = 'a444b05c8fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reviews_book_user', 'reviews', ['user_uid', 'book_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_book_user', 'reviews', type_='unique')
    # ### end Alembic commands ###
